---
title: Tanium
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
    permalink: "/customer-success/case-studies/"
  events:
    title: Events
    output: true
    permalink: "/about/events/"
  news:
    title: News
    output: true
    permalink: "/about/news-and-press/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: resource
    permalink: "/resources/:title/"
    author:
      about headline: 
      authors:
      - name: ''
        image: ''
        bio text: ''
    form:
      id: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
    hero:
      title: ''
      copy: ''
      icon image: ''
      cta:
      - link: ''
        copy: ''
        class: ''
      mobile image: ''
      desktop image: ''
      class: ''
    bottomCTA:
      eyebrow: ''
      title: ''
      cta:
      - link: ''
        copy: ''
        class: ''
      image: ''
      imageLocation: ''
- scope:
    path: home
    type: pages
  values:
    layout: home
    about:
      eyebrow: ''
      title: ''
      copy: ''
      cta:
      - link: ''
        copy: ''
        class: ''
      list:
        item:
          title: ''
          icon: ''
          copy: ''
- scope:
    path: products-and-services
    type: pages
  values:
    layout: products
    hero:
      class: product bg-primary-lt
    intro:
      eyebrow: ''
      text: ''
      video:
        title: ''
        video: ''
        caption: ''
    benefits:
      eyebrow: ''
      title: ''
      benefits:
      - icon image: ''
        title: ''
        text: ''
      - icon image: ''
        title: ''
        text: ''
      - icon image: ''
        title: ''
        text: ''
      cta:
      - link: ''
        copy: ''
        class: ''
      class: ''
    features:
      eyebrow: ''
      title: ''
      features:
      - title: ''
        text: ''
      - title: ''
        text: ''
      - title: ''
        text: ''
      cta:
      - link: ''
        copy: ''
        class: ''
      class: ''
    products:
      eyebrow: Products
      title: Explore Related Products Lorem Ipsum Dolor Sit
      products:
      - title: ''
        icon image: ''
      - title: ''
        icon image: ''
      - title: ''
        icon image: ''
      - title: ''
        icon image: ''
      cta:
      - link: ''
        copy: ''
        class: ''
      class: ''
    resources:
      eyebrow: Resources
      title: Related Content
      count: '3'
      cta:
      - link: ''
        copy: View all content
        class: btn-primary
      class: ''
    bottomCTA:
      eyebrow: Next step
      title: Ready to get started?
      cta:
      - link: ''
        copy: Schedule a demo
        class: ''
      image: ''
      imageLocation: ''
permalink: pretty
copyright: "&copy; 2019 Tanium Inc. All rights reserved. Tanium is a registered trademark
  of Tanium Inc. All other trademarks herein are the property of their respective
  owners."
