---
title: Tanium
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
    permalink: "/about/blog/"
  case-studies:
    title: Case Studies
    output: true
    permalink: "/customer-success/case-studies/"
  events:
    title: Events
    output: true
    permalink: "/about/events/"
  news:
    title: News
    output: true
    permalink: "/about/news-and-press/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    hero:
      title: ''
      copy: ''
      icon: ''
      cta:
        link: ''
        text: ''
      image: ''
      class: ''
    bottomCTA:
      eyebrow: ''
      title: ''
      cta:
        link: ''
        text: ''
      image: ''
      imageLocation: ''
- scope:
    path: home
    type: pages
  values:
    layout: home
    about:
      eyebrow: ''
      title: ''
      copy: ''
      cta:
        link: ''
        text: ''
      list:
        item:
          title: ''
          icon: ''
          copy: ''
- scope:
    path: products-and-services
    type: pages
  values:
    layout: products
    intro:
      eyebrow: ''
      title: ''
      copy: ''
      facts:
        fact:
          figure: ''
          text: ''
    callout:
      title: ''
      copy: ''
      cta:
        link: ''
        text: ''
      image: ''
      imageLocation: ''
    solutions:
      eyebrow: Solutions
      title: Challenges We Solve
      cta:
        link: ''
        text: ''
    industries:
      eyebrow: Industries
      title: Explore Taniums Industries
permalink: pretty
copyright: "&copy; 2019 Tanium Inc. All rights reserved. Tanium is a registered trademark of Tanium Inc. All other trademarks herein are the property of their respective owners."