---
title: Tanium
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  solutions:
    title: Solutions
    output: true
  the-tanium-platform:
    title: The Tanium Platform
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    hero:
      title: ''
      copy: ''
      icon: ''
      cta:
        link: ''
        text: ''
      image: ''
      class: ''
    bottomCTA:
      eyebrow: ''
      title: ''
      cta:
        link: ''
        text: ''
      image: ''
      imageLocation: ''
- scope:
    path: home
    type: pages
  values:
    layout: home
    about:
      eyebrow: ''
      title: ''
      copy: ''
      cta:
        link: ''
        text: ''
      list:
        item:
          title: ''
          icon: ''
          copy: ''
- scope:
    path: solutions
    type: pages
  values:
    intro:
      eyebrow: ''
      title: ''
      copy: ''
      facts:
        fact:
          figure: ''
          text: ''
    callout:
      title: ''
      copy: ''
      cta:
        link: ''
        text: ''
      image: ''
      imageLocation: ''
    solutions:
      eyebrow: Solutions
      title: Challenges We Solve
      cta:
        link: ''
        text: ''
    industries:
      eyebrow: Industries
      title: Explore Taniums Industries
permalink: pretty
